### ISSUE TITLE
Practica 2

### ISSUE THREAD

**Issue by UsuarioIncognito** [SistemasTecTlaxiaco/compuertas-logicas-pavos2#1]
[PRACTICA_2_MATESDISCRETAS.pdf](https://github.com/user-attachments/files/18066935/PRACTICA_2_MATESDISCRETAS.pdf)
)

**Comment by Irwingferia** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
